base_url = "https://jayrovacsek.github.io/north-south-ride"
build_search_index = true
compile_sass = false
generate_feeds = true
minify_html = true
theme = "no-style-please"

[markdown]
highlight_code = false

[extra]
