concurrency:
  group: "deploy"
  cancel-in-progress: false

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: install
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.19.1
      - name: build
        run: zola build
      - name: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy
        id: deploy
        uses: actions/deploy-pages@v4

name: build and deploy

on:
  workflow_run:
    workflows: [checks]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write
